"""removes archived attribute from recruit model;


Revision ID: 0f4f94f0f2f7
Revises: 1b555669d064
Create Date: 2024-08-14 11:54:03.112337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f4f94f0f2f7'
down_revision = '1b555669d064'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recruits', schema=None) as batch_op:
        batch_op.drop_column('archived')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recruits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archived', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
