"""revises touchpoint column to be recruit_id rather than player_id

Revision ID: 21914f436381
Revises: a32dbdd90075
Create Date: 2024-08-08 15:49:32.711302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21914f436381'
down_revision = 'a32dbdd90075'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('touchpoints', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recruit_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('fk_touchpoints_player_id_recruits', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_touchpoints_recruit_id_recruits'), 'recruits', ['recruit_id'], ['id'])
        batch_op.drop_column('player_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('touchpoints', schema=None) as batch_op:
        batch_op.add_column(sa.Column('player_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_touchpoints_recruit_id_recruits'), type_='foreignkey')
        batch_op.create_foreign_key('fk_touchpoints_player_id_recruits', 'recruits', ['player_id'], ['id'])
        batch_op.drop_column('recruit_id')

    # ### end Alembic commands ###
