"""adds meetingType model

Revision ID: 29c0c2d5afe1
Revises: 7a608562b1ad
Create Date: 2024-08-07 09:56:55.527844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29c0c2d5afe1'
down_revision = '7a608562b1ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meetingTypes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meetingTypes'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meetingTypes')
    # ### end Alembic commands ###
