"""adds high priority recruit tag

Revision ID: 3e81353d0afe
Revises: 6b8d6f34c4b4
Create Date: 2024-08-12 14:49:13.783294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e81353d0afe'
down_revision = '6b8d6f34c4b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recruits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('high_priority', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recruits', schema=None) as batch_op:
        batch_op.drop_column('high_priority')

    # ### end Alembic commands ###
