"""removes cell from user model

Revision ID: 4a8a92727f5b
Revises: 4b36405ae6ba
Create Date: 2024-08-12 08:06:59.250662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a8a92727f5b'
down_revision = '4b36405ae6ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('cell')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cell', sa.VARCHAR(), nullable=False))

    # ### end Alembic commands ###
