"""init database

Revision ID: 4b36405ae6ba
Revises: 
Create Date: 2024-08-10 09:18:56.121715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b36405ae6ba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meeting_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meeting_types'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('cell', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('_password_hash', sa.String(), nullable=False),
    sa.Column('notifications', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('recruits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('classYear', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('cell', sa.String(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=True),
    sa.Column('nextTouchpoint', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_recruits_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recruits'))
    )
    op.create_table('touchpoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recruit_id', sa.Integer(), nullable=False),
    sa.Column('meetingType_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['meetingType_id'], ['meeting_types.id'], name=op.f('fk_touchpoints_meetingType_id_meeting_types')),
    sa.ForeignKeyConstraint(['recruit_id'], ['recruits.id'], name=op.f('fk_touchpoints_recruit_id_recruits')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_touchpoints'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('touchpoints')
    op.drop_table('recruits')
    op.drop_table('users')
    op.drop_table('meeting_types')
    # ### end Alembic commands ###
