"""removes notifications attribute from user model

Revision ID: 618dd7530251
Revises: 3e81353d0afe
Create Date: 2024-08-12 16:02:00.463150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '618dd7530251'
down_revision = '3e81353d0afe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('notifications')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notifications', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
