"""adds touchpoint model

Revision ID: dcfd7849d1b3
Revises: ca0bb434ff61
Create Date: 2024-08-07 10:10:20.582326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcfd7849d1b3'
down_revision = 'ca0bb434ff61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('touchpoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('meetingType_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['meetingType_id'], ['meeting_types.id'], name=op.f('fk_touchpoints_meetingType_id_meeting_types')),
    sa.ForeignKeyConstraint(['player_id'], ['recruits.id'], name=op.f('fk_touchpoints_player_id_recruits')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_touchpoints'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('touchpoints')
    # ### end Alembic commands ###
