"""renames touchpoints to contacts

Revision ID: f58c71ec0b1f
Revises: 0f4f94f0f2f7
Create Date: 2024-08-18 14:49:51.668037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f58c71ec0b1f'
down_revision = '0f4f94f0f2f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recruit_id', sa.Integer(), nullable=False),
    sa.Column('meetingType_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['meetingType_id'], ['meeting_types.id'], name=op.f('fk_contacts_meetingType_id_meeting_types')),
    sa.ForeignKeyConstraint(['recruit_id'], ['recruits.id'], name=op.f('fk_contacts_recruit_id_recruits')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contacts'))
    )
    op.drop_table('touchpoints')
    with op.batch_alter_table('recruits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('next_contact', sa.String(), nullable=True))
        batch_op.drop_column('next_touchpoint')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recruits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('next_touchpoint', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('next_contact')

    op.create_table('touchpoints',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('recruit_id', sa.INTEGER(), nullable=False),
    sa.Column('meetingType_id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.VARCHAR(), nullable=False),
    sa.Column('notes', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['meetingType_id'], ['meeting_types.id'], ),
    sa.ForeignKeyConstraint(['recruit_id'], ['recruits.id'], name='fk_touchpoints_recruit_id_recruits'),
    sa.PrimaryKeyConstraint('id', name='pk_touchpoints')
    )
    op.drop_table('contacts')
    # ### end Alembic commands ###
